# Generated by Django 5.1.6 on 2025-03-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedpcroom',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
