# Generated by Django 5.1.6 on 2025-02-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedcomputer',
            unique_together={('computer', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='bookedpcroom',
            unique_together={('pcroom', 'start_time', 'end_time')},
        ),
    ]
