# Generated by Django 5.1.6 on 2025-02-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookedcomputer_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcroom',
            name='computers',
        ),
        migrations.AddField(
            model_name='computer',
            name='pcroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.pcroom'),
        ),
    ]
