# Generated by Django 5.1.6 on 2025-03-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookedpcroom_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedpcroom',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='bookedpcroom',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
