# Generated by Django 5.1.6 on 2025-03-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_pcroom_computers_computer_pcroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcroom',
            old_name='numder',
            new_name='number',
        ),
    ]
