# Generated by Django 5.1.6 on 2025-03-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_numder_pcroom_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedcomputer',
            old_name='user',
            new_name='uprofile',
        ),
        migrations.RenameField(
            model_name='bookedpcroom',
            old_name='user',
            new_name='uprofile',
        ),
    ]
